services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --overprovisioned
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: beauty
      POSTGRES_DB: beauty
    ports:
      - "5432:5432"
