apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer
spec:
  scaleTargetRef:
    name: consumer
  minReplicaCount: 1
  maxReplicaCount: 8
  pollingInterval: 5
  cooldownPeriod: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: redpanda.default.svc.cluster.local:9092
        consumerGroup: ${GROUP}
        topic: ${TOPIC}
        lagThreshold: "2000"
        offsetResetPolicy: earliest
        allowIdleConsumers: "false"
